### PR TITLE
Fix bug #110

### LINKED ISSUE #110: [Bug] Array analyzer for class property
When checking
https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Expression/FunctionCall/RandomApiMigration.php

We get no notice from the ArrayShortDefinition analyzer. However we have a long style definition at $map property.

### PR DESCRIPTION
**Pull request by ddmler**
Resolves #110 
Property defaults now fire an event and get checked too.

### CODE REVIEW

File: src/Definition/ClassDefinition.php [hunk 1]
```diff
@@ -130,6 +130,20 @@ public function compile(Context $context)
         $context->setFilepath($this->filepath);
         $context->setScope($this);
 
+        foreach ($this->properties as $property) {
+            if ($property->default == null) {
```
Comment (ovr) [inline src/Definition/ClassDefinition.php]: Please don't write strict compare, when is not needed, why `if ($property->default` is not okey for you?

File: src/Definition/ClassDefinition.php [hunk 2]
```diff
@@ -130,6 +130,20 @@ public function compile(Context $context)
...
+                continue;
+            }
+            // fire expression event for property default
```
Comment (ovr) [inline src/Definition/ClassDefinition.php]: Blan line needed, before comment

**Comment by ovr** [comment]
@ddmler Thanks you 👍
